Update to using poetry for dependency management.
RewstApp/rewst_remote_agent pull request #6
Opened 2024-01-24 19:08 UTC by mikelane

This change replaces the traditional requirements.txt with a more robust pyproject.toml and poetry.lock for dependency management,
adhering to the latest best practices.

 • Add .gitignore to exclude IDE-specific directories
 • Remove requirements.txt in favor of Poetry's pyproject.toml
 • Update README.md with new Python prerequisite and Poetry commands
 • Introduce pyproject.toml with project metadata and dependencies

2024-01-24 21:18 UTC, tfournet commented
the automated build scripts (build.yml) make use of requirements.txt currently. Will need to update these to use poetry

2024-01-24 21:18 UTC, tfournet requested changes
the automated build scripts (build.yml) make use of requirements.txt currently. Will need to update these to use poetry

2024-01-24 21:20 UTC, mikelane commented
Will take a look at those.

2025-01-16 22:27 UTC, closed without merging

2025-01-16 22:27 UTC, mlataza commented
Will be worked on https://app.shortcut.com/rewst/story/36908/update-build-process-to-not-sign-on-testing-branches